export const STATES = [
    { value: 'Acre', label: 'Acre (AC)' },
    { value: 'Alagoas', label: 'Alagoas (AL)' },
    { value: 'Amapá', label: 'Amapá (AP)' },
    { value: 'Amazonas', label: 'Amazonas (AM)' },
    { value: 'Bahia', label: 'Bahia (BA)' },
    { value: 'Ceará', label: 'Ceará (CE)' },
    { value: 'Distrito Federal', label: 'Distrito Federal (DF)' },
    { value: 'Espírito Santo', label: 'Espírito Santo (ES)' },
    { value: 'Goiás', label: 'Goiás (GO)' },
    { value: 'Maranhão', label: 'Maranhão (MA)' },
    { value: 'Mato Grosso', label: 'Mato Grosso (MT)' },
    { value: 'Mato Grosso do Sul', label: 'Mato Grosso do Sul (MS)' },
    { value: 'Minas Gerais', label: 'Minas Gerais (MG)' },
    { value: 'Pará', label: 'Pará (PA)' },
    { value: 'Paraíba', label: 'Paraíba (PB)' },
    { value: 'Paraná', label: 'Paraná (PR)' },
    { value: 'Pernambuco', label: 'Pernambuco (PE)' },
    { value: 'Piauí', label: 'Piauí (PI)' },
    { value: 'Rio de Janeiro', label: 'Rio de Janeiro (RJ)' },
    { value: 'Rio Grande do Norte', label: 'Rio Grande do Norte (RN)' },
    { value: 'Rio Grande do Sul', label: 'Rio Grande do Sul (RS)' },
    { value: 'Rondônia', label: 'Rondônia (RO)' },
    { value: 'Roraima', label: 'Roraima (RR)' },
    { value: 'Santa Catarina', label: 'Santa Catarina (SC)' },
    { value: 'São Paulo', label: 'São Paulo (SP)' },
    { value: 'Sergipe', label: 'Sergipe (SE)' },
    { value: 'Tocantins', label: 'Tocantins (TO)' },
];